### PR TITLE
Fix getTemperature()

### PR DESCRIPTION
**Pull request by Dracanrage**
I have tested this func in pico, it returns negative value.
I find it forget to change ADC read value to ADC_Voltage, so I made this commit to totally fixed this function, return with double value in centigrade.

### CODE REVIEW

**Comment by pschatzmann** [comment]
Cool - however I would suggest to keep it as int for the following reasons
- analogRead() also provides int
- I would prefer to avoid to give the impression that we can measure temperatures with decimals

What do you think?

**Comment by Dracanrage** [comment]
OK, I will keep it int 😁

**Comment by Dracanrage** [comment]
Committed, it return int value now.

**Comment by pschatzmann** [comment]
Cool ... thanks - it is merged. 

Please note that I plan to rename the function from getTemperature() to temperature() - I guess that the initial name was a old habit from my Java days

**Comment by pschatzmann** [comment]
The rename has been committed and I also provide an official example now:
https://github.com/pschatzmann/pico-arduino/tree/main/examples/temperature_sensor

**Pull request merged**
